name: koshki
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  authentication_repository:
    path: packages/authentication_repository
  form_inputs:
    path: packages/form_inputs
  equatable: ^2.0.5
  cupertino_icons: ^1.0.2
  firebase_core: ^2.16.0
  formz: ^0.6.0
  google_fonts: ^4.0.0
  meta: ^1.7.0
  flutter_bloc: ^8.1.3

dev_dependencies:
  bloc_test: ^9.0.0
  mocktail: ^1.0.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

