// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIhK9jl8p1SEKMeA9KdBLSdKLgk6NZTzM',
    appId: '1:973149770409:web:2e03045ba5948564328fb8',
    messagingSenderId: '973149770409',
    projectId: 'koshki-mirea',
    authDomain: 'koshki-mirea.firebaseapp.com',
    storageBucket: 'koshki-mirea.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLwe2TCaUVJSQHz0oK-yz7wZV5ZtMI4g0',
    appId: '1:973149770409:android:2a61c345ee468915328fb8',
    messagingSenderId: '973149770409',
    projectId: 'koshki-mirea',
    storageBucket: 'koshki-mirea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAvh2dKqsC8_877DAz51NIxVLhzqQYOJ0',
    appId: '1:973149770409:ios:17569a02748cecef328fb8',
    messagingSenderId: '973149770409',
    projectId: 'koshki-mirea',
    storageBucket: 'koshki-mirea.appspot.com',
    iosBundleId: 'com.example.koshki',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAvh2dKqsC8_877DAz51NIxVLhzqQYOJ0',
    appId: '1:973149770409:ios:696ae0931e4438ff328fb8',
    messagingSenderId: '973149770409',
    projectId: 'koshki-mirea',
    storageBucket: 'koshki-mirea.appspot.com',
    iosBundleId: 'com.example.koshki.RunnerTests',
  );
}
